const router = require('express').Router();
let Task = require('../models/task.model');

router.route('/').get((req, res) => {
    // identical to users, we look for all the tasks in the database, then return them
    // in JSON format
    Task.find()
        .then(tasks => res.json(tasks))
        .catch(err => res.status(400).json('Error: ' + err));
});

router.route('/add').post((req, res) => {
    const username = req.body.username;
    const description = req.body.description;
    const duration = Number(req.body.duration);
    const date = Date.parse(req.body.date);

    const newTask = new Task({
        username,
        description,
        duration,
        date,
    });

    newTask.save()
    .then(() => res.json('Task added!'))
    .catch(err => res.status(400).json('Error: ' + err));
});

// adding the rest of the CRUD operations

router.route('/:id').get((req, res) => {
    // /:id is an automatic id generated by MongoDB, calling '/:id', and 
    // making a get request, means that we return the task with that particular id
    Task.findById(req.params.id)
    .then(exercise => res.json(exercise))
    .catch(err => res.status(400).json('Error: ' + json));
});

router.route('/:id').delete((req, res) => {
    // we find the task by ID and delete it
    Task.findByIdAndDelete(req.params.id)
    .then(() => res.json('Exercise deleted.'))
    .catch(err => res.status(400).json('Error: ' + err));
});

router.route('/update/:id').post((req, res) => {
    // updates the task, with the new task information
    Task.findById(req.params.id)
    .then(task => { 
        task.username = req.body.username;
        task.description = req.body.description;
        task.duration = Number(req.body.duration);
        task.date = Date.parse(req.body.date);

        task.save()
            .then(() => res.json('Exercise updated!'))
            .catch(err => res.status(400).json('Error' + err));
    })
    .catch(err => res.status(400).json('Error: ' + err));
});

module.exports = router;

